# Vanilla Hyprland config (hyprlang format)
$mod = SUPER

source = ~/.config/hypr/lua/monitors.conf
source = ~/.config/hypr/lua/env.conf

# Autostart
source = ~/.config/hypr/lua/execs.conf

# Input / binds settings
source = ~/.config/hypr/lua/input.conf

source = ~/.config/hypr/lua/general.conf
source = ~/.config/hypr/lua/decoration.conf
source = ~/.config/hypr/lua/animations.conf

# Misc / xwayland
source = ~/.config/hypr/lua/misc.conf

source = ~/.config/hypr/lua/windowrules.conf
source = ~/.config/hypr/lua/keybinds.conf
