neofetch

bindkey -v

export ZSH="$HOME/.oh-my-zsh"
plugins=(git vi-mode archlinux zsh-syntax-highlighting zsh-autosuggestions)
source $ZSH/oh-my-zsh.sh

export PATH="$PATH:$HOME/.cargo/bin"

export GOPATH="${HOME}/go"
export PATH="$PATH:$HOME/go/bin"

# User configuration
export EDITOR='nvim'
export HISTFILESIZE=100000
export HISTSIZE=${HISTFILESIZE}
source $HOME/Projects/dotfiles/aliases

eval "$(zoxide init zsh)"
eval "$(starship init zsh)"
eval "$(atuin init zsh --disable-up-arrow)"
