# General + layout — sourced from hyprland.conf.
general {
    gaps_in = 5
    gaps_out = 5
    border_size = 2
    col.active_border = rgba(89b4faee) rgba(cba6f7ee) 45deg
    col.inactive_border = rgba(595959aa)
    layout = dwindle
}

dwindle {
    force_split = 2
    preserve_split = true
    pseudotile = true
}
