-- General + dwindle layout — sourced from hyprland.lua
-- Border colors come from colors.lua (auto-generated by scheme-sync-hyprland).
-- Fallback to Catppuccin defaults if the file hasn't been generated yet.
local ok, theme = pcall(dofile, os.getenv("HOME") .. "/.config/hypr/lua/colors.lua")
if not ok then
	theme = { primary = "89b4fa", secondary = "cba6f7", outline = "595959" }
end

hl.config({
	general = {
		gaps_in = 5,
		gaps_out = 5,
		border_size = 2,
		col = {
			active_border = { colors = { "rgba(" .. theme.primary .. "ee)", "rgba(" .. theme.secondary .. "ee)" }, angle = 45 },
			inactive_border = "rgba(" .. theme.outline .. "66)",
		},
		layout = "dwindle",
		resize_on_border = true, -- hover na borda → resize cursor
	},

	dwindle = {
		force_split = 2,
		preserve_split = true,
	},
})
